version: '3.7'

services:
  blazor-angelo:
    container_name: blazor-angelo
    build: .
    restart: always
    volumes:
      - /docker/angelo/data:/app
    ports: 
      - 5090:5001
    networks:
      - lan-network

networks:
  lan-network:
    external:
      name: docker-net