// <auto-generated />
using Blazor.PersonalWebSites.Server.Models.Services.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blazor.MyWebsites.Server.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    [Migration("20220209182328_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("Blazor.MyWebsites.Shared.Models.Entities.CompetenzaPersonale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaTecnica")
                        .HasColumnType("TEXT");

                    b.Property<string>("Competenza")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompetenzePersonali");
                });

            modelBuilder.Entity("Blazor.MyWebsites.Shared.Models.Entities.CompetenzaTecnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaTecnica")
                        .HasColumnType("TEXT");

                    b.Property<string>("Competenza")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompetenzeTecniche");
                });

            modelBuilder.Entity("Blazor.MyWebsites.Shared.Models.Entities.CorsoOnline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Certificato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Corso")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataRilascio")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataScadenza")
                        .HasColumnType("TEXT");

                    b.Property<string>("Piattaforma")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CorsiOnline");
                });

            modelBuilder.Entity("Blazor.MyWebsites.Shared.Models.Entities.EsperienzaProfessionale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Azienda")
                        .HasColumnType("TEXT");

                    b.Property<string>("Esperienza")
                        .HasColumnType("TEXT");

                    b.Property<string>("Luogo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Periodo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EsperienzeProfessionali");
                });
#pragma warning restore 612, 618
        }
    }
}
